"""empty message

Revision ID: 28d97222a296
Revises: 5c1c5753149c
Create Date: 2021-03-13 12:18:21.030258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d97222a296'
down_revision = '5c1c5753149c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('routeName', sa.String(length=120), nullable=True),
    sa.Column('mapPointNames', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_routes_city'), 'map_routes', ['city'], unique=False)
    op.create_index(op.f('ix_map_routes_mapPointNames'), 'map_routes', ['mapPointNames'], unique=False)
    op.create_index(op.f('ix_map_routes_routeName'), 'map_routes', ['routeName'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_map_routes_routeName'), table_name='map_routes')
    op.drop_index(op.f('ix_map_routes_mapPointNames'), table_name='map_routes')
    op.drop_index(op.f('ix_map_routes_city'), table_name='map_routes')
    op.drop_table('map_routes')
    # ### end Alembic commands ###
