"""empty message

Revision ID: 5c1c5753149c
Revises: 5f01d694a630
Create Date: 2021-03-13 12:02:33.120152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1c5753149c'
down_revision = '5f01d694a630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_points', sa.Column('city', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_map_points_city'), 'map_points', ['city'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_map_points_city'), table_name='map_points')
    op.drop_column('map_points', 'city')
    # ### end Alembic commands ###
