"""empty message

Revision ID: 5f01d694a630
Revises: a90fd353dbf2
Create Date: 2021-03-12 16:04:21.975713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f01d694a630'
down_revision = 'a90fd353dbf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_map_points_name', table_name='map_points')
    op.create_index(op.f('ix_map_points_name'), 'map_points', ['name'], unique=False)
    op.drop_index('ix_map_points_pointX', table_name='map_points')
    op.create_index(op.f('ix_map_points_pointX'), 'map_points', ['pointX'], unique=False)
    op.drop_index('ix_map_points_pointY', table_name='map_points')
    op.create_index(op.f('ix_map_points_pointY'), 'map_points', ['pointY'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_map_points_pointY'), table_name='map_points')
    op.create_index('ix_map_points_pointY', 'map_points', ['pointY'], unique=1)
    op.drop_index(op.f('ix_map_points_pointX'), table_name='map_points')
    op.create_index('ix_map_points_pointX', 'map_points', ['pointX'], unique=1)
    op.drop_index(op.f('ix_map_points_name'), table_name='map_points')
    op.create_index('ix_map_points_name', 'map_points', ['name'], unique=1)
    # ### end Alembic commands ###
