"""empty message

Revision ID: 8bd045ec71c1
Revises: 28d97222a296
Create Date: 2021-03-14 11:28:06.712476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd045ec71c1'
down_revision = '28d97222a296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_points', sa.Column('description', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_map_points_description'), 'map_points', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_map_points_description'), table_name='map_points')
    op.drop_column('map_points', 'description')
    # ### end Alembic commands ###
